### ISSUE TITLE
Async signal/slot

### ISSUE THREAD

**Issue by ashf** [fritzone/miso#1]
With QT you can put a QObject on a QThread and emit a signal to a slot for that QObject. This allows asynchronicity, since an object on Thread-A can emit a signal to a slot of an object on Thread-B. 

Is there any way to replicate that functionality with Miso?

Currently I do the connection like this:
`connect(objB->signal, std::bind(&ObjA::slot, objA, std::placeholders::_1));
`

But I don't know how to put the objB onto a separate thread nicely with Miso.

**Comment by fritzone** [comment]
Hi, unfortunately miso is a very small project, without the supporting underlying infrastructure of Qt, so with the current functionality it is not possible to achieve what you are aiming for :(
